# Generated by Django 5.1.5 on 2026-03-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
