# Generated by Django 5.1.5 on 2026-03-05 23:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lecturepdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturepdf',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
