# Generated by Django 5.1.5 on 2026-03-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lecturepdf_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturepdf',
            name='pdf_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
