# Generated by Django 5.1.5 on 2026-03-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lecturepdf_pdf_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturepdf',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
