# Generated by Django 5.1.5 on 2026-03-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lecturepdf_file_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturepdf',
            name='questions',
        ),
        migrations.AddField(
            model_name='lecturepdf',
            name='quiz',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
