# Generated by Django 5.1.5 on 2026-03-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_lecturepdf_questions_lecturepdf_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturepdf',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecturepdf',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturepdf',
            name='user_answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
